// Surah list for the Quran tab.
// Arabic names, revelation place and verse counts come from the Tanzil Project
// Uthmani text (https://tanzil.net), via github.com/dotquran/corpus (CC BY 3.0).
// Transliterated names and name meanings (en / ru) were added separately.

export type Surah = {
  number: number
  name: string
  meaning: string
  verses: number
  arabicName: string
  place: "meccan" | "medinan"
}

export const surahs: Surah[] = [
  {
    number: 1,
    name: "Al-Fatihah",
    meaning: "The Opening",
    verses: 7,
    arabicName: "الفاتحة",
    place: "meccan",
  },
  {
    number: 2,
    name: "Al-Baqarah",
    meaning: "The Cow",
    verses: 286,
    arabicName: "البقرة",
    place: "medinan",
  },
  {
    number: 3,
    name: "Ali 'Imran",
    meaning: "Family of Imran",
    verses: 200,
    arabicName: "آل عمران",
    place: "medinan",
  },
  {
    number: 4,
    name: "An-Nisa",
    meaning: "The Women",
    verses: 176,
    arabicName: "النساء",
    place: "medinan",
  },
  {
    number: 5,
    name: "Al-Ma'idah",
    meaning: "The Table Spread",
    verses: 120,
    arabicName: "المائدة",
    place: "medinan",
  },
  {
    number: 6,
    name: "Al-An'am",
    meaning: "The Cattle",
    verses: 165,
    arabicName: "الأنعام",
    place: "meccan",
  },
  {
    number: 7,
    name: "Al-A'raf",
    meaning: "The Heights",
    verses: 206,
    arabicName: "الأعراف",
    place: "meccan",
  },
  {
    number: 8,
    name: "Al-Anfal",
    meaning: "The Spoils of War",
    verses: 75,
    arabicName: "الأنفال",
    place: "medinan",
  },
  {
    number: 9,
    name: "At-Tawbah",
    meaning: "The Repentance",
    verses: 129,
    arabicName: "التوبة",
    place: "medinan",
  },
  {
    number: 10,
    name: "Yunus",
    meaning: "Jonah",
    verses: 109,
    arabicName: "يونس",
    place: "meccan",
  },
  {
    number: 11,
    name: "Hud",
    meaning: "Hud",
    verses: 123,
    arabicName: "هود",
    place: "meccan",
  },
  {
    number: 12,
    name: "Yusuf",
    meaning: "Joseph",
    verses: 111,
    arabicName: "يوسف",
    place: "meccan",
  },
  {
    number: 13,
    name: "Ar-Ra'd",
    meaning: "The Thunder",
    verses: 43,
    arabicName: "الرعد",
    place: "medinan",
  },
  {
    number: 14,
    name: "Ibrahim",
    meaning: "Abraham",
    verses: 52,
    arabicName: "إبراهيم",
    place: "meccan",
  },
  {
    number: 15,
    name: "Al-Hijr",
    meaning: "The Rocky Tract",
    verses: 99,
    arabicName: "الحجر",
    place: "meccan",
  },
  {
    number: 16,
    name: "An-Nahl",
    meaning: "The Bee",
    verses: 128,
    arabicName: "النحل",
    place: "meccan",
  },
  {
    number: 17,
    name: "Al-Isra",
    meaning: "The Night Journey",
    verses: 111,
    arabicName: "الإسراء",
    place: "meccan",
  },
  {
    number: 18,
    name: "Al-Kahf",
    meaning: "The Cave",
    verses: 110,
    arabicName: "الكهف",
    place: "meccan",
  },
  {
    number: 19,
    name: "Maryam",
    meaning: "Mary",
    verses: 98,
    arabicName: "مريم",
    place: "meccan",
  },
  {
    number: 20,
    name: "Ta-Ha",
    meaning: "Ta-Ha",
    verses: 135,
    arabicName: "طه",
    place: "meccan",
  },
  {
    number: 21,
    name: "Al-Anbiya",
    meaning: "The Prophets",
    verses: 112,
    arabicName: "الأنبياء",
    place: "meccan",
  },
  {
    number: 22,
    name: "Al-Hajj",
    meaning: "The Pilgrimage",
    verses: 78,
    arabicName: "الحج",
    place: "medinan",
  },
  {
    number: 23,
    name: "Al-Mu'minun",
    meaning: "The Believers",
    verses: 118,
    arabicName: "المؤمنون",
    place: "meccan",
  },
  {
    number: 24,
    name: "An-Nur",
    meaning: "The Light",
    verses: 64,
    arabicName: "النور",
    place: "medinan",
  },
  {
    number: 25,
    name: "Al-Furqan",
    meaning: "The Criterion",
    verses: 77,
    arabicName: "الفرقان",
    place: "meccan",
  },
  {
    number: 26,
    name: "Ash-Shu'ara",
    meaning: "The Poets",
    verses: 227,
    arabicName: "الشعراء",
    place: "meccan",
  },
  {
    number: 27,
    name: "An-Naml",
    meaning: "The Ants",
    verses: 93,
    arabicName: "النمل",
    place: "meccan",
  },
  {
    number: 28,
    name: "Al-Qasas",
    meaning: "The Stories",
    verses: 88,
    arabicName: "القصص",
    place: "meccan",
  },
  {
    number: 29,
    name: "Al-'Ankabut",
    meaning: "The Spider",
    verses: 69,
    arabicName: "العنكبوت",
    place: "meccan",
  },
  {
    number: 30,
    name: "Ar-Rum",
    meaning: "The Romans",
    verses: 60,
    arabicName: "الروم",
    place: "meccan",
  },
  {
    number: 31,
    name: "Luqman",
    meaning: "Luqman",
    verses: 34,
    arabicName: "لقمان",
    place: "meccan",
  },
  {
    number: 32,
    name: "As-Sajdah",
    meaning: "The Prostration",
    verses: 30,
    arabicName: "السجدة",
    place: "meccan",
  },
  {
    number: 33,
    name: "Al-Ahzab",
    meaning: "The Combined Forces",
    verses: 73,
    arabicName: "الأحزاب",
    place: "medinan",
  },
  {
    number: 34,
    name: "Saba",
    meaning: "Sheba",
    verses: 54,
    arabicName: "سبأ",
    place: "meccan",
  },
  {
    number: 35,
    name: "Fatir",
    meaning: "The Originator",
    verses: 45,
    arabicName: "فاطر",
    place: "meccan",
  },
  {
    number: 36,
    name: "Ya-Sin",
    meaning: "Ya-Sin",
    verses: 83,
    arabicName: "يس",
    place: "meccan",
  },
  {
    number: 37,
    name: "As-Saffat",
    meaning: "Those Ranged in Ranks",
    verses: 182,
    arabicName: "الصافات",
    place: "meccan",
  },
  {
    number: 38,
    name: "Sad",
    meaning: "Sad",
    verses: 88,
    arabicName: "ص",
    place: "meccan",
  },
  {
    number: 39,
    name: "Az-Zumar",
    meaning: "The Groups",
    verses: 75,
    arabicName: "الزمر",
    place: "meccan",
  },
  {
    number: 40,
    name: "Ghafir",
    meaning: "The Forgiver",
    verses: 85,
    arabicName: "غافر",
    place: "meccan",
  },
  {
    number: 41,
    name: "Fussilat",
    meaning: "Explained in Detail",
    verses: 54,
    arabicName: "فصلت",
    place: "meccan",
  },
  {
    number: 42,
    name: "Ash-Shura",
    meaning: "The Consultation",
    verses: 53,
    arabicName: "الشورى",
    place: "meccan",
  },
  {
    number: 43,
    name: "Az-Zukhruf",
    meaning: "The Gold Adornments",
    verses: 89,
    arabicName: "الزخرف",
    place: "meccan",
  },
  {
    number: 44,
    name: "Ad-Dukhan",
    meaning: "The Smoke",
    verses: 59,
    arabicName: "الدخان",
    place: "meccan",
  },
  {
    number: 45,
    name: "Al-Jathiyah",
    meaning: "The Kneeling",
    verses: 37,
    arabicName: "الجاثية",
    place: "meccan",
  },
  {
    number: 46,
    name: "Al-Ahqaf",
    meaning: "The Wind-Curved Sandhills",
    verses: 35,
    arabicName: "الأحقاف",
    place: "meccan",
  },
  {
    number: 47,
    name: "Muhammad",
    meaning: "Muhammad",
    verses: 38,
    arabicName: "محمد",
    place: "medinan",
  },
  {
    number: 48,
    name: "Al-Fath",
    meaning: "The Victory",
    verses: 29,
    arabicName: "الفتح",
    place: "medinan",
  },
  {
    number: 49,
    name: "Al-Hujurat",
    meaning: "The Rooms",
    verses: 18,
    arabicName: "الحجرات",
    place: "medinan",
  },
  {
    number: 50,
    name: "Qaf",
    meaning: "Qaf",
    verses: 45,
    arabicName: "ق",
    place: "meccan",
  },
  {
    number: 51,
    name: "Adh-Dhariyat",
    meaning: "The Winnowing Winds",
    verses: 60,
    arabicName: "الذاريات",
    place: "meccan",
  },
  {
    number: 52,
    name: "At-Tur",
    meaning: "The Mount",
    verses: 49,
    arabicName: "الطور",
    place: "meccan",
  },
  {
    number: 53,
    name: "An-Najm",
    meaning: "The Star",
    verses: 62,
    arabicName: "النجم",
    place: "meccan",
  },
  {
    number: 54,
    name: "Al-Qamar",
    meaning: "The Moon",
    verses: 55,
    arabicName: "القمر",
    place: "meccan",
  },
  {
    number: 55,
    name: "Ar-Rahman",
    meaning: "The Most Merciful",
    verses: 78,
    arabicName: "الرحمن",
    place: "medinan",
  },
  {
    number: 56,
    name: "Al-Waqi'ah",
    meaning: "The Inevitable",
    verses: 96,
    arabicName: "الواقعة",
    place: "meccan",
  },
  {
    number: 57,
    name: "Al-Hadid",
    meaning: "The Iron",
    verses: 29,
    arabicName: "الحديد",
    place: "medinan",
  },
  {
    number: 58,
    name: "Al-Mujadilah",
    meaning: "The Pleading Woman",
    verses: 22,
    arabicName: "المجادلة",
    place: "medinan",
  },
  {
    number: 59,
    name: "Al-Hashr",
    meaning: "The Gathering",
    verses: 24,
    arabicName: "الحشر",
    place: "medinan",
  },
  {
    number: 60,
    name: "Al-Mumtahanah",
    meaning: "The Woman to Be Examined",
    verses: 13,
    arabicName: "الممتحنة",
    place: "medinan",
  },
  {
    number: 61,
    name: "As-Saff",
    meaning: "The Ranks",
    verses: 14,
    arabicName: "الصف",
    place: "medinan",
  },
  {
    number: 62,
    name: "Al-Jumu'ah",
    meaning: "The Congregation",
    verses: 11,
    arabicName: "الجمعة",
    place: "medinan",
  },
  {
    number: 63,
    name: "Al-Munafiqun",
    meaning: "The Hypocrites",
    verses: 11,
    arabicName: "المنافقون",
    place: "medinan",
  },
  {
    number: 64,
    name: "At-Taghabun",
    meaning: "The Mutual Disillusion",
    verses: 18,
    arabicName: "التغابن",
    place: "medinan",
  },
  {
    number: 65,
    name: "At-Talaq",
    meaning: "The Divorce",
    verses: 12,
    arabicName: "الطلاق",
    place: "medinan",
  },
  {
    number: 66,
    name: "At-Tahrim",
    meaning: "The Prohibition",
    verses: 12,
    arabicName: "التحريم",
    place: "medinan",
  },
  {
    number: 67,
    name: "Al-Mulk",
    meaning: "The Sovereignty",
    verses: 30,
    arabicName: "الملك",
    place: "meccan",
  },
  {
    number: 68,
    name: "Al-Qalam",
    meaning: "The Pen",
    verses: 52,
    arabicName: "القلم",
    place: "meccan",
  },
  {
    number: 69,
    name: "Al-Haqqah",
    meaning: "The Reality",
    verses: 52,
    arabicName: "الحاقة",
    place: "meccan",
  },
  {
    number: 70,
    name: "Al-Ma'arij",
    meaning: "The Ascending Stairways",
    verses: 44,
    arabicName: "المعارج",
    place: "meccan",
  },
  {
    number: 71,
    name: "Nuh",
    meaning: "Noah",
    verses: 28,
    arabicName: "نوح",
    place: "meccan",
  },
  {
    number: 72,
    name: "Al-Jinn",
    meaning: "The Jinn",
    verses: 28,
    arabicName: "الجن",
    place: "meccan",
  },
  {
    number: 73,
    name: "Al-Muzzammil",
    meaning: "The Enshrouded One",
    verses: 20,
    arabicName: "المزمل",
    place: "meccan",
  },
  {
    number: 74,
    name: "Al-Muddaththir",
    meaning: "The Cloaked One",
    verses: 56,
    arabicName: "المدثر",
    place: "meccan",
  },
  {
    number: 75,
    name: "Al-Qiyamah",
    meaning: "The Resurrection",
    verses: 40,
    arabicName: "القيامة",
    place: "meccan",
  },
  {
    number: 76,
    name: "Al-Insan",
    meaning: "The Human",
    verses: 31,
    arabicName: "الإنسان",
    place: "medinan",
  },
  {
    number: 77,
    name: "Al-Mursalat",
    meaning: "The Emissaries",
    verses: 50,
    arabicName: "المرسلات",
    place: "meccan",
  },
  {
    number: 78,
    name: "An-Naba",
    meaning: "The Tidings",
    verses: 40,
    arabicName: "النبأ",
    place: "meccan",
  },
  {
    number: 79,
    name: "An-Nazi'at",
    meaning: "Those Who Drag Forth",
    verses: 46,
    arabicName: "النازعات",
    place: "meccan",
  },
  {
    number: 80,
    name: "'Abasa",
    meaning: "He Frowned",
    verses: 42,
    arabicName: "عبس",
    place: "meccan",
  },
  {
    number: 81,
    name: "At-Takwir",
    meaning: "The Overthrowing",
    verses: 29,
    arabicName: "التكوير",
    place: "meccan",
  },
  {
    number: 82,
    name: "Al-Infitar",
    meaning: "The Cleaving",
    verses: 19,
    arabicName: "الانفطار",
    place: "meccan",
  },
  {
    number: 83,
    name: "Al-Mutaffifin",
    meaning: "The Defrauding",
    verses: 36,
    arabicName: "المطففين",
    place: "meccan",
  },
  {
    number: 84,
    name: "Al-Inshiqaq",
    meaning: "The Splitting Open",
    verses: 25,
    arabicName: "الانشقاق",
    place: "meccan",
  },
  {
    number: 85,
    name: "Al-Buruj",
    meaning: "The Constellations",
    verses: 22,
    arabicName: "البروج",
    place: "meccan",
  },
  {
    number: 86,
    name: "At-Tariq",
    meaning: "The Nightcomer",
    verses: 17,
    arabicName: "الطارق",
    place: "meccan",
  },
  {
    number: 87,
    name: "Al-A'la",
    meaning: "The Most High",
    verses: 19,
    arabicName: "الأعلى",
    place: "meccan",
  },
  {
    number: 88,
    name: "Al-Ghashiyah",
    meaning: "The Overwhelming",
    verses: 26,
    arabicName: "الغاشية",
    place: "meccan",
  },
  {
    number: 89,
    name: "Al-Fajr",
    meaning: "The Dawn",
    verses: 30,
    arabicName: "الفجر",
    place: "meccan",
  },
  {
    number: 90,
    name: "Al-Balad",
    meaning: "The City",
    verses: 20,
    arabicName: "البلد",
    place: "meccan",
  },
  {
    number: 91,
    name: "Ash-Shams",
    meaning: "The Sun",
    verses: 15,
    arabicName: "الشمس",
    place: "meccan",
  },
  {
    number: 92,
    name: "Al-Layl",
    meaning: "The Night",
    verses: 21,
    arabicName: "الليل",
    place: "meccan",
  },
  {
    number: 93,
    name: "Ad-Duha",
    meaning: "The Morning Hours",
    verses: 11,
    arabicName: "الضحى",
    place: "meccan",
  },
  {
    number: 94,
    name: "Ash-Sharh",
    meaning: "The Relief",
    verses: 8,
    arabicName: "الشرح",
    place: "meccan",
  },
  {
    number: 95,
    name: "At-Tin",
    meaning: "The Fig",
    verses: 8,
    arabicName: "التين",
    place: "meccan",
  },
  {
    number: 96,
    name: "Al-'Alaq",
    meaning: "The Clot",
    verses: 19,
    arabicName: "العلق",
    place: "meccan",
  },
  {
    number: 97,
    name: "Al-Qadr",
    meaning: "The Power",
    verses: 5,
    arabicName: "القدر",
    place: "meccan",
  },
  {
    number: 98,
    name: "Al-Bayyinah",
    meaning: "The Clear Proof",
    verses: 8,
    arabicName: "البينة",
    place: "medinan",
  },
  {
    number: 99,
    name: "Az-Zalzalah",
    meaning: "The Earthquake",
    verses: 8,
    arabicName: "الزلزلة",
    place: "medinan",
  },
  {
    number: 100,
    name: "Al-'Adiyat",
    meaning: "The Courser",
    verses: 11,
    arabicName: "العاديات",
    place: "meccan",
  },
  {
    number: 101,
    name: "Al-Qari'ah",
    meaning: "The Calamity",
    verses: 11,
    arabicName: "القارعة",
    place: "meccan",
  },
  {
    number: 102,
    name: "At-Takathur",
    meaning: "Competition",
    verses: 8,
    arabicName: "التكاثر",
    place: "meccan",
  },
  {
    number: 103,
    name: "Al-'Asr",
    meaning: "The Declining Day",
    verses: 3,
    arabicName: "العصر",
    place: "meccan",
  },
  {
    number: 104,
    name: "Al-Humazah",
    meaning: "The Traducer",
    verses: 9,
    arabicName: "الهمزة",
    place: "meccan",
  },
  {
    number: 105,
    name: "Al-Fil",
    meaning: "The Elephant",
    verses: 5,
    arabicName: "الفيل",
    place: "meccan",
  },
  {
    number: 106,
    name: "Quraysh",
    meaning: "Quraysh",
    verses: 4,
    arabicName: "قريش",
    place: "meccan",
  },
  {
    number: 107,
    name: "Al-Ma'un",
    meaning: "Small Kindnesses",
    verses: 7,
    arabicName: "الماعون",
    place: "meccan",
  },
  {
    number: 108,
    name: "Al-Kawthar",
    meaning: "Abundance",
    verses: 3,
    arabicName: "الكوثر",
    place: "meccan",
  },
  {
    number: 109,
    name: "Al-Kafirun",
    meaning: "The Disbelievers",
    verses: 6,
    arabicName: "الكافرون",
    place: "meccan",
  },
  {
    number: 110,
    name: "An-Nasr",
    meaning: "Divine Support",
    verses: 3,
    arabicName: "النصر",
    place: "medinan",
  },
  {
    number: 111,
    name: "Al-Masad",
    meaning: "The Palm Fiber",
    verses: 5,
    arabicName: "المسد",
    place: "meccan",
  },
  {
    number: 112,
    name: "Al-Ikhlas",
    meaning: "Sincerity",
    verses: 4,
    arabicName: "الإخلاص",
    place: "meccan",
  },
  {
    number: 113,
    name: "Al-Falaq",
    meaning: "The Daybreak",
    verses: 5,
    arabicName: "الفلق",
    place: "meccan",
  },
  {
    number: 114,
    name: "An-Nas",
    meaning: "Mankind",
    verses: 6,
    arabicName: "الناس",
    place: "meccan",
  },
]

export const surahMeaningsEn = [
  "The Opening",
  "The Cow",
  "Family of Imran",
  "The Women",
  "The Table Spread",
  "The Cattle",
  "The Heights",
  "The Spoils of War",
  "The Repentance",
  "Jonah",
  "Hud",
  "Joseph",
  "The Thunder",
  "Abraham",
  "The Rocky Tract",
  "The Bee",
  "The Night Journey",
  "The Cave",
  "Mary",
  "Ta-Ha",
  "The Prophets",
  "The Pilgrimage",
  "The Believers",
  "The Light",
  "The Criterion",
  "The Poets",
  "The Ants",
  "The Stories",
  "The Spider",
  "The Romans",
  "Luqman",
  "The Prostration",
  "The Combined Forces",
  "Sheba",
  "The Originator",
  "Ya-Sin",
  "Those Ranged in Ranks",
  "Sad",
  "The Groups",
  "The Forgiver",
  "Explained in Detail",
  "The Consultation",
  "The Gold Adornments",
  "The Smoke",
  "The Kneeling",
  "The Wind-Curved Sandhills",
  "Muhammad",
  "The Victory",
  "The Rooms",
  "Qaf",
  "The Winnowing Winds",
  "The Mount",
  "The Star",
  "The Moon",
  "The Most Merciful",
  "The Inevitable",
  "The Iron",
  "The Pleading Woman",
  "The Gathering",
  "The Woman to Be Examined",
  "The Ranks",
  "The Congregation",
  "The Hypocrites",
  "The Mutual Disillusion",
  "The Divorce",
  "The Prohibition",
  "The Sovereignty",
  "The Pen",
  "The Reality",
  "The Ascending Stairways",
  "Noah",
  "The Jinn",
  "The Enshrouded One",
  "The Cloaked One",
  "The Resurrection",
  "The Human",
  "The Emissaries",
  "The Tidings",
  "Those Who Drag Forth",
  "He Frowned",
  "The Overthrowing",
  "The Cleaving",
  "The Defrauding",
  "The Splitting Open",
  "The Constellations",
  "The Nightcomer",
  "The Most High",
  "The Overwhelming",
  "The Dawn",
  "The City",
  "The Sun",
  "The Night",
  "The Morning Hours",
  "The Relief",
  "The Fig",
  "The Clot",
  "The Power",
  "The Clear Proof",
  "The Earthquake",
  "The Courser",
  "The Calamity",
  "Competition",
  "The Declining Day",
  "The Traducer",
  "The Elephant",
  "Quraysh",
  "Small Kindnesses",
  "Abundance",
  "The Disbelievers",
  "Divine Support",
  "The Palm Fiber",
  "Sincerity",
  "The Daybreak",
  "Mankind",
]

export const surahMeaningsRu = [
  "Открывающая [Коран]",
  "Корова",
  "Семейство ‘Имрана",
  "Женщины",
  "Трапеза",
  "Скот",
  "Преграды",
  "Трофеи",
  "Покаяние",
  "Пророк Юнус",
  "Пророк Худ",
  "Пророк Юсуф",
  "Гром",
  "Пророк Ибрахим",
  "Аль-Хиджр",
  "Пчёлы",
  "Ночное путешествие",
  "Пещера",
  "Марьям",
  "Та. Ха.",
  "Пророки",
  "Хадж",
  "Верующие",
  "Свет",
  "Различение",
  "Поэты",
  "Муравьи",
  "Повествование",
  "Паук",
  "Ромеи",
  "Лукман",
  "Преклонение ниц",
  "Союзные племена",
  "Царство Саба",
  "Изначально сотворивший",
  "Йа. Син",
  "Выстроившиеся рядами",
  "Сад",
  "Толпы",
  "Прощающий",
  "Разъяснены",
  "Совет",
  "Украшения",
  "Дым",
  "Коленопреклонённая",
  "Аль-Ахкаф",
  "Пророк Мухаммад",
  "Победа",
  "Комнаты",
  "Каф",
  "Рассеивающие",
  "Гора",
  "Звезда",
  "Луна",
  "Всемилостивый",
  "Событие",
  "Железо",
  "Пререкающаяся",
  "Сбор",
  "Испытуемая",
  "Ряд",
  "Пятница",
  "Лицемеры",
  "Взаимный убыток",
  "Развод",
  "Запрещение",
  "Владычество",
  "Писчее перо",
  "Неминуемое",
  "Ступени возвышения",
  "Пророк Нух",
  "Джинны",
  "Закутавшийся",
  "Укрывшийся",
  "Воскресение",
  "Человек",
  "Посылаемые",
  "Весть",
  "Вырывающие",
  "Нахмурился",
  "Сворачивание",
  "Раскалывание",
  "Уменьшающие меру и вес",
  "Раскалывание",
  "Созвездия",
  "Ночной путник",
  "Высочайший",
  "Покрывающее",
  "Заря",
  "Город Мекка",
  "Солнце",
  "Ночь",
  "Утреннее время",
  "Раскрытие груди",
  "Смоковница",
  "Сгусток крови",
  "Предопределение",
  "Ясное доказательство",
  "Землетрясение",
  "Мчащиеся",
  "Поражающее",
  "Стремление к приумножению",
  "Предвечерье",
  "Хулители",
  "Слон",
  "Курайшиты",
  "Малая помощь",
  "Аль-Каусар",
  "Отвергшие веру",
  "Помощь",
  "Верёвка из пальмовых волокон",
  "Искренность",
  "Рассвет",
  "Люди",
]

// Bismillah, shown as its own unnumbered line above the verses (standard in printed mushafs).
// Verbatim from the Tanzil data, where it is "verse 0" of surahs 2-114 (except 9).
export const BISMILLAH = "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ"

// In the Tanzil data, Al-Fatihah (1) counts the bismillah as verse 1, and At-Tawbah (9) has none.
// In At-Tin (95) and Al-Qadr (97) the bismillah is glued to the front of verse 1.
const BISMILLAH_MERGED_INTO_VERSE_1 = [95, 97]
const BISMILLAH_WORD_COUNT = 4

export function surahShowsBismillah(surahNumber: number) {
  return surahNumber !== 1 && surahNumber !== 9
}

// Returns the verse texts ready for display: same words, same order, nothing changed or dropped,
// except that the bismillah glued to verse 1 of surahs 95 and 97 is moved to its own line.
export function prepareVerses(surahNumber: number, verses: string[]) {
  if (!BISMILLAH_MERGED_INTO_VERSE_1.includes(surahNumber)) return verses
  const words = verses[0].split(" ")
  return [words.slice(BISMILLAH_WORD_COUNT).join(" "), ...verses.slice(1)]
}
